const howItWorkQ = [
  {
    question: "What is GoldenCity?",
    answer: "GoldenCity is an innovative investment project dedicated to real estate. We allow clients to invest as little as $10 in investment properties, with the aim of building up regular income and/or savings."
  },
  {
    question: "What are the conditions for investing on GoldenCity?",
    answer: "Any person of legal age can hold a GoldenCity NFT! Investing is simple - you merely need to have VeChain wallet and you are ready to buy one or more GoldenCity NFTs."
  },
  {
    question: "Can I invest with a company or SCI?",
    answer: "Of course you can! As for an individual you need the same things, i.e. to hold one or more GoldenCity NFTs."
  },
  {
    question: "How are the properties selected?",

    answer: "We select and negotiate the acquisition of rental or investment propertiess, and soon abroad. We do our utmost to guarantee a selection of quality rental projects and optimal risk control.  Each operation is rigorously evaluated by our real estate experts, according to strict criteria including:  i. the occupancy rate of the building and its net rental return on the day of acquisition ii. the general condition of the building and the common areas iii. the cost of maintenance and renovation work iv. the energy performance v. the quality of the neighbourhood vi. the geographical location of the building vii. the proximity of essential services (shops, schools, public transport, etc.) viii. key indicators such as demographics, rental pressure and the evolution of property prices in the area."
  },
  {
    question: "Do you become a homeowner by buying NFTs on GoldenCity?",
    answer: "When you buy NFTs on GoldenCity, you are not actually buying part of a property, nor do you become an owner. You hold royalties, which means that you are entitled to receive a royalty on the rents and capital gains generated by the property in which you invest. The amount of these royalties is paid to you every month, depending on the number of NFTs you own. The advantage: an immediate return on investment with income paid every month (linked to the rents collected), without the management, financing or tax constraints associated with traditional rental investment!"
  },
  {
    question: "When buying NFTs, do we benefit from the bank leverage effect?",

    answer: "Yes, most of the properties we offer on our platform do not have a bank loan but some are co-financed with a bank loan. Borrowing from the bank allows us to leverage the bank and increase the profitability of the investments."
  },
  {
    question: "Can buying NFTs reduce my borrowing capacity?",

    answer: "Absolutely not. The bank loans used to finance the projects are carried by our company. The purchase of NFTs therefore has no impact on your debt ratio or borrowing capacity."
  },
  {

    question: "How is the property revaluation carried out?",

    answer: "Because the value of a property can vary over time, each of our properties is revalued every year by an independent, TEGoVA-accredited property expert. These valuations take into account changes in the property market and any work carried out on the property. They allow the value of the NFTs to be revalued upwards or downwards. This ensures that your money is invested in property that is fairly valued."
  },
  {

    question: "I want to buy NFTs, what payment methods are accepted?",

    answer: "You can use various payment methods such as Metamask, Phantom wallet, OKX wallet, Trust wallet, etc."
  },
  {

    question: "Is it possible to cancel my NFT purchase?",

    answer: "At the moment it is not possible to get the NFT refunded after the purchase, but with time we will try to implement this function with a liquidity pool. After signing the deed of sale at the notary's office, you can sell your NFTs to other investors on our Marketplace (secondary market)."
  },
  {

    question: 'What is the difference between "Profitability" and "Return on investment"?',

    answer: 'The "Return on investment" corresponds to the excess part of the rents which will be paid to you after deduction of the amortization of the expenses, and, if necessary, the GoldenCityayment of credit. The "Profitability" corresponds to the returned income to which are added the real estate capital gain and the mechanical increase in the price of the NFT due to the amortization of the real estate loan present on the property in question.'
  }
]

export default howItWorkQ;