import LocalizedStrings from "react-localization";

const localized = new LocalizedStrings({
  ru: {
    successfully: "Успешно",
    unsuccessful: "Неуспешно",
    error: "Неизвестная ошибка, обновите страницу и попробуйте еще раз",
    enter: "Войти",
    authorization: "Авторизация",
    errorName: "Введите имя от 3 символов",
    nickname: "Ваш ник",
    errorPassword: "Введите пароль от 5 символов",
    password: "Пароль",
    language: "Язык",
    register: "Зарегистрироваться",
    gameDemonstration: "Демонстрация игры",
    mobileErrorTitle: "Приложение недоступно",
    mobileErrorText:
      "Мобильная версия приложения находится в разработке. Пожалуйста, откройте приложение на большом экране",
    next: "Далее",
    play: "Играть",
    message: "Сообщение",
    send: "Отправить",
    reload: "Обновить",
    close: "Закрыть",
    sendThank: "Отправлено, спасибо",
    myEmail: "Моя почта:",
    suggest: "Предложение",
    yourSuggest: "Введите ваше предложение",
    haveSuggest: "Есть предложение?",
    problemDesc: "Описание проблемы",
    descProblem: "Опишите проблему",
    haveProblem: "Нашли проблему?",
    yourEmail: "Ваш email",
    emailError: "Введите корректный email",
    optionalField: "Необязательное поле",
    commentPlease:
      "Пожалуйста, напишите ваш отзыв или комментарий, мне очень важно его услышать",
    money: "Деньги",
    healing: "Лечение",
    air: "Воздух",
    earth: "Земля",
    water: "Вода",
    fire: "Огонь",
    sword: "Меч",
    health: "Здоровье",
    experience: "Опыт",
    lvl: "Уровень",
    name: "Имя",
    noData: "Нет данных",
    changeLanguage: "Поменять язык",
    exit: "Выйти из аккаунта",
    howExp: "Как получить опыт",
    hit: "Удар",
    damage: "Урона",
    whatExp: "Что дает опыт",
    lvls: "Уровни",
    chat: "Чат",
    closeChat: "Закрыть чат",

    roxy: "Рокси",
    paul: "Пол",
    zenith: "Зенит",
    lilia: "Лилия",
    hooligan: "Хулиган",
    silphi: "Сильфи",
    wolf: "Волк",
    hunter: "Охотник",
    villagers: "Селяне",
    bandit: "Бандит",

    rating: "Рейтинг игроков",
    info: "Информация",
    feedback: "Обратная связь",
    development: "Разработка",
    talk: "Разговор",
    training: "Тренировка",

    paulHouse: "Дом Пола",
    buenaFields: "Поля Буэна",
    hoolFight: "Бой с хулиганом",
    buena: "Деревня Буэна",
    buenaForest: "Леса Буэна",
    banditFight: "Бой с бандитом",
    roaRoad: "Дорога в Роа",
    wolfFight: "Бой с волком",

    swordHit: "Удар мечем",
    fireHit: "Магия огня",
    waterHit: "Магия воды",
    earthHit: "Магия земли",
    airHit: "Магия воздуха",
    chooses: "Выбирает",
    yourTurn: "Сейчас ваш ход!",
    soundOn: "Включить звук",
    soundOff: "Выключить звук",
    escape: "Сбежать",
    escapeText: "Вы сбежали с поля боя",
    whatAttak: "Чем будет атаковать",
    noHp: "Потеряв способность сражаться вы сбежали с поля боя",
    youWin: "Вы победили",
    noExp: "И не получили опыта",
    yesExp: "И получили",
    mon: "Монет:",
    expSword: "Опыт мечника:",
    expFire: "Опыт мага огня:",
    expWater: "Опыт мага воды:",
    expEarth: "Опыт мага земли:",
    expAir: "Опыт мага воздуха:",
    expHeal: "Опыт целителя:",

    news: "Новости",
    obt: "Открытый Бета Тест",
    new1: "С 13 января 2024 года стартует ОБТ Браузерной ММОРПГ по мотивам Реинкарнация Безработного, можно снова окунуться в прекрасный мир Mushoku Tensei, оказаться в знакомых и любимых локациях, встретиться с Богиней Рокси, сразиться с бандитами и волками! Вперёд!",

    quest1:
      "Это ты, Рудеус Грейрат, поздравляем, ты родился в мире меча и магии, монстров, подземелий, приключений",
    quest2:
      "Это твои родители, Пол Грейрат и Зенит Грейрат. Оба бывшие исследователи подземелий самого высокого ранга. Зенит высококлассный целитель, а Пол мастерски владеет мечом",
    quest3:
      "Ты рос, как обычный ребёнок, ползал, ходил, бегал, изучал окружающий мир, играл в прятки с Зенит. Ничего интересного не происходило, но однажды...",
    quest4:
      "Ты упал и ударился головой, а Зенит вылечила тебя своей магией исцеления. Ты узнал, что в этом мире есть магия! Это сильно заинтересовало маленького Рудеуса и навсегда изменило твоё будущее",
    quest5:
      "Каждый день ты усердно тренировался, изучал магическую литературу, пытался колдовать, было сложно и получалось не сразу, но результат упорного труда был достигнут",
    quest6:
      "Ты научился создавать водные шары разного размера, далеко запускать их, а один раз у тебя даже получилось создать такой огромный водный шаг, что он разрушил окно!",
    quest7:
      "Зенит настояла, чтобы тебе наняли репетитора магии. Им стала маленькая девочка по имени Рокси, она очень хороша в магии воды и готова учить тебя, но будь готов много тренироваться! Чтобы начать занятия, поговори с Рокси",

    questFooter1: "Поговори с Рокси Мигурдией",
    questFooter2: "Получи по 10 опыта мага воды, огня, воздуха, земли",
    questFooter3: "Поговори с Полом",
    questFooter4: "Получи 30 опыта мечника тренируясь с Полом",
    questFooter5: "Поговори с Зенит",
    questFooter6: "Получи 30 опыта лекаря тренируясь с Зенит",
    questFooter7: "Попить чай с Лилией",
    questFooter8: "Найти друзей в деревне Буэна",
    questFooter9: "Победи 5 хулиганов в деревне Буэна",
    questFooter10: "Проведи с Сильфи 10 тренировочных боев",
    questFooter11: "Поговори с селянами в полях Буэна",
    questFooter12: "Победи 10 бандитов в полях Буэна",
    questFooter13: "Поговори с охотником в лесах Буэна",
    questFooter14: "Победи 10 волков в лесах Буэна",
    questFooter15: "Поговори с Рокси",
    questFooter16: "Получи по 200 опыта каждой магии",
    questFooter17: "Поговори с Полом",
    questFooter18: "Получи 200 опыта мечника",
    questFooter19: "Поговори с Зенит",
    questFooter20: "Получи 200 опыта лекаря",
    questFooter21: "Квесты выполнены, ждите новую главу!",

    developmentTitle1: "Что сделано:",
    developmentTitle2: "Что будет сделано:",

    developmentNow1: "Регистрация и вход в игру",
    developmentNow2: "Переход по локациям",
    developmentNow3: "12 локаций деревни Буэна",
    developmentNow4: "Бой с NPC и мобами",
    developmentNow5: "Прокачка персонажа",
    developmentNow6: "20 квестов и разговоры с NPC",
    developmentNow7: "Рейтинг игроков",
    developmentNow8: "Общий чат",
    developmentNow9: "Вся музыка 1 сезона",
    developmentNow10: "Вспомогательные страницы",
    developmentNow11: "Локализация на 2 языка",

    developmentFuture1: "Сюжетная линия с Эрис",
    developmentFuture2: "Локации региона Роа",
    developmentFuture3: "Рюкзак",
    developmentFuture4: "Броня и оружие",
    developmentFuture5: "Гильдия авантюристов",
    developmentFuture6: "Профессии",
    developmentFuture7: "Подземелья",
    developmentFuture8: "Зелья",
    developmentFuture9: "Атакующие предметы",
    developmentFuture10: "Магазин",
    developmentFuture11: "Группы",
    developmentFuture12: "Гильдии",
    developmentFuture13: "Cовместное убийство мобов",
    developmentFuture14: "Добавление боссов",
    developmentFuture15: "Перенос мобов на карту охоты",
    developmentFuture16: "Дом который можно улучшать",
    developmentFuture17: "Глобальная карта",
    developmentFuture18: "Личные сообщения",
    developmentFuture19: "Игроки по локациям",
    developmentFuture20: "Комбинации ударов",
    developmentFuture21: "Интерактивная карта",
    developmentFuture22: "PVP",
    developmentFuture23: "Поля битв, арены",
    developmentFuture24: "Мана",
    developmentFuture25: "PVP валюта",
    developmentFuture26: "Аукцион",
    developmentFuture27: "Сбор ресурсов",
    developmentFuture28: "Второстепенные задания",

    q11: "Привет, ученик, сегодня мы начинаем наши занятия. Я Святой Маг Воды, Рокси Мигурдия, буду учить тебя магии воды",
    q12: "Рокси ждёт тебя! Поговори с ней",
    q21: "Лучшее обучение это поединки, я буду тебе поддаваться. Задание на сегодня: получили по 10 опыта мага воды, огня, воздуха, земли, тренируясь со мной, для этого надо атаковать меня каждой магией по 10 раз!",
    q22: "Рокси ждёт тебя! Получили по 10 опыта каждой из магий, тренируясь с Рокси, для этого надо атаковать её каждой стихией по 10 раз",
    q31: "Ты хорошо справился с прошлым заданием, молодец! Ты получил по 10 опыта каждой стихии магии, это увечило твоё здоровье на 4 пункта и увеличило урон магией, 10 опыта дают 1 урон. Чем больше ты тренируешься в какой-либо области, тем сильнее ты становишься! Теперь поговори с Полом, он уже приготовил мечи для тренировки",
    q32: "Привет, Руди! Понравились уроки магией? Теперь у нас уроки с мечом!",
    q33: "Пол ждёт тебя! Поговори с ним",
    q41: "Тебе надо атаковать меня мечом 30 раз, тогда ты получишь немного опыта и станешь сильнее, сейчас ты совсем слабак, поэтому буду поддаваться тебе",
    q42: "Пол ждёт тебя! Получили 30 опыта мечника, тренируясь с Полом, для этого надо атаковать его мечом 30 раз",
    q51: "Ты хорошо справился с прошлым заданием, молодец! Ты получил 30 опыта мечника, это увечило твоё здоровье на 3 пункта и увеличило урон мечом также на 3. Чем больше ты тренируешься в какой-либо области, тем сильнее ты становишься! Теперь поговори с Зенит, она хочет чтобы ты стал лучше в магии исцеления",
    q52: "Привет, Руди! Понравились уроки с мечом? Теперь займёмся магией лечения",
    q53: "Зенит ждёт тебя! Поговори с ней",
    q61: "Ты должен получить 30 опыта в магии лечения, я буду тебя атаковать, а ты лечи себя, если не можешь больше сражаться, просто убеги, но если сможешь, победи меня",
    q62: "Зенит ждёт тебя! Получили 30 опыта лекаря, тренируясь с Зенит, для этого надо вылечить себя 30 раз",
    q71: "Молодец, сынок! Ты хорошо справился, теперь сможешь подлечить себя в любой сложной ситуации. Помни, магия лечения очень полезна! Ты можешь лечить себя и друзей. А теперь поговори с Лилией, она хотела тебя увидеть",
    q72: "Привет, Руди, как дела? Тётушка Лилия заварила твой любимый чай, не хочешь выпить? Он ещё горячий и очень вкусный, как ты любишь!",
    q73: "Лилия ждёт тебя! Попей с ней чай, она хочет тебя увидеть",
    q81: "Я хотела поговорить с тобой. В твоем возрасте уже пора иметь друзей, хватит быть затворником. Погуляй по деревне и найди себе друга, в нашей деревне много детей твоего возраста",
    q82: "Привет! Меня зовут Сильфи, у меня зелёные волосы и никто не дружит со мной, из-за этого мне очень одиноко. Но ты не похож на других, давай дружить? Спасибо!",
    q83: "Найди друзей в деревне, хватит быть затворником",
    q91: "О нет! Опять на меня напали хулиганы! Спаси меня от них! Они издеваются надо мной каждый день, закидывают камнями и грязью, мне очень нужна твоя помощь! Их пятеро против меня одной! Пожалуйста, победи 5 хулиганов и спаси маленькую зеленоволосую девочку!",
    q92: "Сильфи нужна твоя помощь! Победи 5 хулиганов, иначе её замучают эти злые дети",
    q101: "Спасибо большое за помощь! Давай дружить? Научи меня магии, пожалуйста! Я не хочу быть слабачкой, которую все обижают, помоги, помоги! Проведи со мной 10 тренировочных боёв",
    q102: "Учитель Рудеус-сама, хе-хе, чего ты тут забыл? Научи Сильфи магии",
    q111: "Ура! Ура! Теперь я тоже могу колдовать! Рудеус спасибо тебе огромное! Но у меня есть ещё одна просьба, поговори пожалуйста с селянами в полях, им очень нужна твоя помощь, бандиты не дают им покоя, только ты с твоей магией можем им помочь",
    q112: "Спасибо, что пришли, маг Рудеус, нам очень нужна ваша помощь",
    q113: "Поговори с селянами, они ждут твоей помощи! Бандиты совсем не дают им покоя",
    q121: "Бандиты нападают на нас и забирают припасы, мы не можем их поймать, мы слабые крестьяне, а вы владеете такой мощной магией! Победите 10 бандитов, тогда они на время отстанут от нас, вы наша единственная надежда",
    q122: "Помоги селянам, победи 10 бандитов, иначе селяне не смогут спокойно жить и работать",
    q131: "Спасибо вам огромное, что помогли нам! Теперь бандиты долго не будут нас беспокоить. Но это ещё не всё... Охотнику в лесу очень нужна помощь, волки атакуют нашу деревню, скоро охотник не сможет их сдерживать! Ему очень нужна ваша магия",
    q132: "Привет, я охотник, волков стало так много, что я не справляюсь с ними, очень нужна твоя помощь",
    q133: "Охотник в лесу Буэна ждет твоей помощи! Поговори с ним",
    q141: "Убей 10 волков, но учти, это настоящие монстры, у них страшные клыши и когти, будь осторожен. Удачи!",
    q142: "Волки атакуют деревню Буэна! Пока что они ещё в лесу, но скоро нападут! Убей 10 волков, пока они не напали на жителей",
    q151: "Ты победил всех волков, молодец! Благодаря твоей помощи деревня в безопасности. Волк - настоящий монстр, но впереди тебя ждут действительно сложные противники, тебе нужно улучшать твои навыки боя, Рокси хотела поговорить с тобой, найди её",
    q152: "Ты вернулся, Рудеус, слышала, что ты победил многих врагов в деревни Буена, поздравляю, ты молодец!",
    q153: "Тебе нужно стать сильнее, поговори с Рокси, она научит тебя магии",
    q161: "Но тебе ещё далеко от меня! Поэтому задание: получи по 200 опыта каждой магии, можешь тренироваться со мной, можешь побеждать врагов, на твой выбор",
    q162: "Получи по 200 опыта в каждой из магии, тебе нужно стать сильнее! Хватит прохлаждаться",
    q171: "Молодец! 200 опыта в каждой из магии это суммарно 800 опыта, которые дают тебе 80 урона и 80 здоровья, ты уже настоящий маг! Но ты еще должен улучшить свои навыки мечника, поэтому поговори с Полом",
    q172: "Привет, привет, неплохо, ты победил слабеньких бандитов и маленьких волчат",
    q173: "Получи по 200 опыта в каждой из магии, тебе нужно стать сильнее! Хватит прохлаждаться",
    q181: "Но тебе еще учиться и учиться! До папки очень далеко, поэтому давай тренироваться, получи 200 опыта мечника, можешь выбрать поединки со мной или побеждать врагов",
    q182: "Получи 200 опыта мечника, ты должен улучшить свои навыки владения мечом",
    q191: "Неплохо, побеждаешь своего папку, но я поддаюсь тебе, чтобы ты не впал в депрессию от бесконечных поражений, но твои навыки владения мечом немного улучшились, поэтому иди к Зенит и поговори с ней о магии лечения",
    q192: "Руди, ты стал таким взрослым! Настоящий воин!",
    q193: "Получи 200 опыта мечника, ты должен улучшить свои навыки владения мечом",
    q201: "Но даже настоящему воину нужно подлечивать себя в бою, поэтому ты должен получить 200 опыта в магии лечения. Лечение - это очень важный навык, который много раз спасёт тебе жизнь",
    q202: "Получи 200 опыта лекаря, хорошие навыки лечения много раз спасут тебя!",
    q211: "Ты такой молодец! Смог получить 200 опыта во всех навыках! Твоя мама гордится тобой, Руди, улучшай свои навыки дальше, чтобы стать сильнее и защитить тех, кто тебе дорог, а Пол пока найдёт тебе работу в качестве репетитора магии",
    q212: "Привет! Как дела? У меня замечательно! Солнышко светит, птички поют, жизнь на природе - просто сказка! Но это мне можно расслабиться, тебе ни в коем случае нельзя расслабляться! Иди и прокачивай свои навыки, ты должен стать сильнее!",

    screenshot1:
      "Тренируйся с Рокси, Зенит, Полом, Сильфи, сражайся с хулиганами, волками, бандитами, прокачивайся! Используй магию огня, воды, земли, ветра, магию исцеления и меч!",
    screenshot2:
      "Изучай локации! Дом Пола, деревня Буена, поля Буена, леса, окрестные дороги",
    screenshot3:
      "Выполняй задания, помогай селянам и друзьям, спаси деревню Буена и её жителей!",
    screenshot4:
      "Соревнуйся с другими игроками в опыте. Пока ты спишь, враг качается! У кого будет больше опыта и денег? Это должен быть ты! Используй вспомогательные страницы и напиши автору проекта, буду ждать",

    USER_NOT_FOUND: "Такой пользователь не зарегистрирован",
    BAD_PASSWORD: "Введён неверный пароль",
    USER_ALREADY_REGISTERED: "Пользователь с таким именем уже существует",
    OTHER_DATA: "Пожалуйста введите другие данные",
    REG_ERROR: "Ошибка при регистрации, попробуйте ещё раз",
    LOGIN_ERROR: "Ошибка при входе, попробуйте ещё раз",
    USER_ERROR: "Ошибка при получении данных пользователя, обновите страницу",
    USERS_ERROR: "Ошибка при получении пользователей, обновите страницу",
    LOCATION_ERROR:
      "Ошибка при смене локации, обновите страницу и поменяйте локацию ещё раз",
    QUEST_ERROR:
      "Ошибка при сдачи задания, обновите страницу и сдайте задание ещё раз",
    LANG_ERROR:
      "Ошибка при смене языка, обновите страницу и поменяйте язык ещё раз",
    EXP_ERROR: "Ошибка при получении опыта, победите противника ещё раз",
    CHAT_ERROR: "Ошибка при написании в чат, напишите сообщение ещё раз",
    CHATS_ERROR:
      "Ошибка при получении сообщений чата, нажмите кнопку «обновить» ещё раз",
    SUGGEST_ERROR:
      "Ошибка при отправке предложения, отправьте ваше предложение ещё раз",
    PROBLEM_ERROR:
      "Ошибка при отправке проблемы, отправьте вашу проблему ещё раз",
  },
  en: {
    successfully: "Successfully",
    unsuccessful: "Unsuccessful",
    error: "Unknown error, please refresh the page and try again",
    enter: "Login",
    authorization: "Authorization",
    errorName: "Enter a name of at least 3 characters",
    nickname: "Your nickname",
    errorPassword: "Enter a password of 5 characters or more",
    password: "Password",
    language: "Language",
    register: "Register",
    gameDemonstration: "Game Demonstration",
    mobileErrorTitle: "Application unavailable",
    mobileErrorText:
      "The mobile version of the application is under development. Please open the application on a larger screen",
    next: "Next",
    play: "Play",
    message: "Message",
    send: "Send",
    reload: "Refresh",
    close: "Close",
    sendThank: "Sent, thank you",
    myEmail: "My email:",
    suggest: "Suggestion",
    yourSuggest: "Enter your suggestion",
    haveSuggest: "Have a suggestion?",
    problemDesc: "Description of the problem",
    descProblem: "Describe the problem",
    haveProblem: "Found a problem?",
    yourEmail: "Your email",
    emailError: "Please enter a valid email",
    optionalField: "Optional field",
    commentPlease:
      "Please write your review or comment, it is very important for me to hear it",
    money: "Money",
    healing: "Healing",
    air: "Air",
    earth: "Earth",
    water: "Water",
    fire: "Fire",
    sword: "Sword",
    health: "Health",
    experience: "Experience",
    lvl: "Level",
    name: "Name",
    noData: "No data",
    changeLanguage: "Change language",
    exit: "Exit account",
    howExp: "How to gain experience",
    hit: "Hit",
    damage: "Damage",
    whatExp: "What experience gives",
    lvls: "Levels",
    chat: "Chat",
    closeChat: "Close chat",

    roxy: "Roxy",
    paul: "Paul",
    zenith: "Zenith",
    lilia: "Lily",
    hooligan: "Hooligan",
    silphi: "Sylphie",
    wolf: "Wolf",
    hunter: "Hunter",
    villagers: "Villages",
    bandit: "Bandit",

    rating: "Player rating",
    info: "Information",
    feedback: "Feedback",
    development: "Development",
    talk: "Conversation",
    training: "Training",

    paulHouse: "Paul's House",
    buenaFields: "Buena Fields",
    hoolFight: "Fight with a bully",
    buena: "Village of Buena",
    buenaForest: "Buena Forests",
    banditFight: "Fight with a bandit",
    roaRoad: "Road to Roa",
    wolfFight: "Fight with a wolf",

    swordHit: "Sword's hit",
    fireHit: "Fire Magic",
    waterHit: "Water Magic",
    earthHit: "Earth Magic",
    airHit: "Air Magic",
    chooses: "Chooses",
    yourTurn: "Now it's your turn!",
    soundOn: "Enable sound",
    soundOff: "Mute sound",
    escape: "Escape",
    escapeText: "You have escaped the battlefield",
    whatAttak: "What will attack with",
    noHp: "Having lost the ability to fight, you fled the battlefield",
    youWin: "You win",
    noExp: "And received no experience",
    yesExp: "And received",
    mon: "Coins:",
    expSword: "Swordsman experience:",
    expFire: "Fire mage experience:",
    expWater: "Waterbender experience:",
    expEarth: "Earthbender experience:",
    expAir: "Airbender experience:",
    expHeal: "Healer experience:",

    news: "News",
    obt: "Open Beta Test",
    new1: "From January 13, 2024, the OBT of the Browser MMORPG based on the Reincarnation of the Unemployed will start, you can again plunge into the wonderful world of Mushoku Tensei, find yourself in familiar and favorite locations, meet the Goddess Roxy, fight bandits and wolves! Let's go!",

    quest1:
      "It's you, Rudeus Greyrat, congratulations, you were born into the world of sword and sorcery, monsters, dungeons, adventures",
    quest2:
      "These are your parents, Paul Greyrat and Zenith Greyrat. Both are former dungeon explorers of the highest rank. Zenith is a highly skilled healer, and Paul is a master swordsman",
    quest3:
      "You grew up like an ordinary child, crawled, walked, ran, explored the world around you, played hide and seek with Zenith. Nothing interesting happened, but one day...",
    quest4:
      "You fell and hit your head, and Zenith healed you with her healing magic. You learned that there is magic in this world! This greatly interested little Rudeus and changed your future forever",
    quest5:
      "Every day you trained hard, studied magical literature, tried to cast a spell, it was difficult and it didnt work right away, but the result of hard work was achieved",
    quest6:
      "You learned how to create water balls of different sizes, launch them far, and once you even managed to create such a huge water step that it destroyed a window!",
    quest7:
      "Zenith insisted that you hire a magic tutor. It was a little girl named Roxy, she is very good at water magic and is ready to teach you, but be prepared to practice a lot! To start classes, talk to Roxy",

    questFooter1: "Talk to Roxy Migurdia",
    questFooter2: "Get 10 water, fire, air, and earth mage experience",
    questFooter3: "Talk to Paul",
    questFooter4: "Get 30 sword experience by training with Paul",
    questFooter5: "Talk to Zenith",
    questFooter6: "Get 30 healer experience by training with Zenith",
    questFooter7: "Drink tea with Lily",
    questFooter8: "Find friends in Buena Village",
    questFooter9: "Defeat 5 bullies in Buena Village",
    questFooter10: "Do 10 practice battles with Sylphy",
    questFooter11: "Talk to the villagers in Buena Fields",
    questFooter12: "Defeat 10 bandits in Buena Fields",
    questFooter13: "Talk to the hunter in Buena Woods",
    questFooter14: "Defeat 10 wolves in Buena Woods",
    questFooter15: "Talk to Roxy",
    questFooter16: "Get 200 experience for each magic",
    questFooter17: "Talk to Paul",
    questFooter18: "Get 200 swordsman experience",
    questFooter19: "Talk to Zenith",
    questFooter20: "Get 200 healer experience",
    questFooter21: "Quests completed, wait for the new chapter!",

    developmentTitle1: "What's done:",
    developmentTitle2: "What will be done:",

    developmentNow1: "Registration and login to the game",
    developmentNow2: "Go to locations",
    developmentNow3: "12 Buena Village locations",
    developmentNow4: "Combat with NPCs and mobs",
    developmentNow5: "Character leveling",
    developmentNow6: "20 quests and conversations with NPCs",
    developmentNow7: "Player rating",
    developmentNow8: "General chat",
    developmentNow9: "All music from season 1",
    developmentNow10: "Support pages",
    developmentNow11: "Localization into 2 languages",

    developmentFuture1: "Storyline with Eris",
    developmentFuture2: "Roa Region Locations",
    developmentFuture3: "Backpack",
    developmentFuture4: "Armor and weapons",
    developmentFuture5: "Adventurers Guild",
    developmentFuture6: "Professions",
    developmentFuture7: "Dungeons",
    developmentFuture8: "Potions",
    developmentFuture9: "Attack items",
    developmentFuture10: "Store",
    developmentFuture11: "Groups",
    developmentFuture12: "Guilds",
    developmentFuture13: "Joint mob killing",
    developmentFuture14: "Adding bosses",
    developmentFuture15: "Transferring mobs to the hunting map",
    developmentFuture16: "A house that can be improved",
    developmentFuture17: "Global Map",
    developmentFuture18: "Private messages",
    developmentFuture19: "Players by location",
    developmentFuture20: "Strike Combinations",
    developmentFuture21: "Interactive map",
    developmentFuture22: "PVP",
    developmentFuture23: "Battlefields, arenas",
    developmentFuture24: "Mana",
    developmentFuture25: "PVP currency",
    developmentFuture26: "Auction",
    developmentFuture27: "Gathering resources",
    developmentFuture28: "Minor quests",

    q11: "Hello, student, today we begin our classes. I am the Holy Mage of Water, Roxy Migurdia, I will teach you water magic",
    q12: "Roxy is waiting for you! Talk to her",
    q21: "The best training is duels, I will give in to you. Task for today: you got 10 experience each as a water, fire, air, and earth magician by training with me, for this you need to attack me with each magic 10 times!",
    q22: "Roxy is waiting for you! We received 10 experience for each magic by training with Roxy, to do this you need to attack her with each element 10 times",
    q31: "You did well on the last task, well done! You received 10 experience for each element of magic, this increased your health by 4 points and increased magic damage, 10 experience gives 1 damage. The more you train in any area, the stronger you become! Now talk to Paul, he's already prepared the swords for training",
    q32: "Hi, Rudy! Did you like the magic lessons? Now we have sword lessons!",
    q33: "Paul is waiting for you! Talk to him",
    q41: "You need to attack me with a sword 30 times, then you will gain a little experience and become stronger, now you are completely weak, so I will give in to you",
    q42: "Paul is waiting for you! You received 30 sword experience by training with Paul, to do this you need to attack him with a sword 30 times",
    q51: "You did well on the last task, well done! You received 30 sword experience, this increased your health by 3 points and increased sword damage by 3 as well. The more you train in any area, the stronger you become! Now talk with Zenith, she wants you to become better at healing magic",
    q52: "Hey Rudy! Did you like the sword lessons? Now let's do healing magic",
    q53: "Zenith is waiting for you! Talk to her",
    q61: "You must get 30 experience in healing magic, I will attack you and you heal yourself, if you can't fight anymore, just run away, but if you can, defeat me",
    q62: "Zenith is waiting for you! You received 30 healer experience by training with Zenith, to do this you need to heal yourself 30 times",
    q71: "Well done, son! You did well, now you can heal yourself in any difficult situation. Remember, healing magic is very useful! You can heal yourself and your friends. Now talk to Lilia, she wanted to see you",
    q72: "Hello, Rudy, how are you? Aunt Lily has made your favorite tea, would you like to drink it? Its still hot and very tasty, just the way you like it!",
    q73: "Lily is waiting for you! Drink tea with her, she wants to see you",
    q81: "I wanted to talk to you. At your age, its time to have friends, stop being a recluse. Take a walk around the village and find yourself a friend, there are many children your age in our village",
    q82: "Hello! My name is Sylphy, I have green hair and no one is friends with me, because of this I feel very lonely. But you are not like others, let's be friends? Thank you!",
    q83: "Find friends in the village, stop being a recluse",
    q91: "Oh no! The hooligans attacked me again! Save me from them! They mock me every day, throw stones and dirt at me, I really need your help! There are five of them against me alone! Please defeat 5 hooligans and save the little green-haired girl!",
    q92: "Sylphy needs your help! Defeat 5 bullies, otherwise she will be tortured by these evil children",
    q101: "Thank you very much for your help! Lets be friends? Teach me magic, please! I dont want to be a weakling who everyone offends, help, help! Spend 10 training battles with me",
    q102: "Teacher Rudeus-sama, hehe, what are you forgetting here? Teach Sylphy magic",
    q111: "Hurray! Hurray! Now I can cast magic too! Rudeus, thank you very much! But I have one more request, please talk to the villagers in the fields, they really need your help, the bandits do not give them peace, only you and your magic we can help them",
    q112: "Thank you for coming, magician Rudeus, we really need your help",
    q113: "Talk to the villagers, they are waiting for your help! The bandits do not give them any peace",
    q121: "Bandits are attacking us and taking supplies, we cant catch them, we are weak peasants, and you have such powerful magic! Defeat 10 bandits, then they will leave us behind for a while, you are our only hope",
    q122: "Help the villagers, defeat 10 bandits, otherwise the villagers will not be able to live and work in peace",
    q131: "Thank you so much for helping us! Now the bandits wont bother us for a long time. But thats not all... A hunter in the forest really needs help, wolves are attacking our village, soon the hunter will not be able to hold them back! He really needs yours magic",
    q132: "Hello, Im a hunter, there are so many wolves that I cant cope with them, I really need your help",
    q133: "The hunter in Buena Forest is waiting for your help! Talk to him",
    q141: "Kill 10 wolves, but remember, these are real monsters, they have terrible fangs and claws, be careful. Good luck!",
    q142: "Wolves are attacking the village of Buena! For now they are still in the forest, but they will attack soon! Kill 10 wolves before they attack the villagers",

    q151: "You defeated all the wolves, well done! Thanks to your help, the village is safe. The wolf is a real monster, but there are really difficult opponents ahead of you, you need to improve your fighting skills, Roxy wanted to talk to you, find her",
    q152: "You're back, Rudeus, I heard that you defeated many enemies in the village of Buena, congratulations, you did great!",
    q153: "You need to become stronger, talk to Roxy, she will teach you magic",
    q161: "But you are still far from me! Therefore, the task: get 200 experience for each magic, you can train with me, you can defeat enemies of your choice",
    q162: "Get 200 experience in each of the magic, you need to become stronger! Stop slacking off",
    q171: "Well done! 200 experience in each magic is a total of 800 experience, which gives you 80 damage and 80 health, you are already a real magician! But you still need to improve your sword skills, so talk to Paul",
    q172: "Hello, hello, not bad, you defeated weak bandits and little wolf cubs",
    q173: "Get 200 experience in each of the magic, you need to become stronger! Stop slacking off",
    q181: "But you still have to study and study! The folder is very far away, so lets train, get 200 sword experience, you can choose fights with me or defeat enemies",
    q182: "Get 200 sword experience, you should improve your sword skills",
    q191: "Not bad, you defeat your dad, but I give in to you so that you don't get depressed from endless defeats, but your sword skills have improved a little, so go to Zenith and talk to her about healing magic",
    q192: "Rudy, you have become so grown up! A real warrior!",
    q193: "Get 200 sword experience, you should improve your sword skills",
    q201: "But even a real warrior needs to heal himself in battle, so you must get 200 experience in healing magic. Healing is a very important skill that will save your life many times",
    q202: "Get 200 healer experience, good healing skills will save you many times!",
    q211: "You're so good! You were able to get 200 experience in all your skills! Your mom is proud of you, Rudy, improve your skills further to become stronger and protect those you care about, and in the meantime, Paul will find you a job as a magic tutor",
    q212: "Hello! How are you? Im doing great! The sun is shining, the birds are singing, life in nature is just a fairy tale! But I can relax, you should never relax! Go and upgrade your skills, you must become stronger! ",

    screenshot1:
      "Train with Roxy, Zenith, Paul, Sylphy, fight with hooligans, wolves, bandits, upgrade! Use fire, water, earth, wind, healing magic and a sword!",
    screenshot2:
      "Explore the locations! Paul's house, Buena village, Buena fields, forests, surrounding roads",
    screenshot3:
      "Complete tasks, help villagers and friends, save the village of Buena and its inhabitants!",
    screenshot4:
      "Compete with other players in experience. While you are sleeping, the enemy is leveling up! Who will have more experience and money? It should be you! Use the support pages and write to the author of the project, I will be waiting",

    USER_NOT_FOUND: "This user is not registered",
    BAD_PASSWORD: "Invalid password entered",
    USER_ALREADY_REGISTERED: "A user with this name already exists",
    OTHER_DATA: "Please enter other data",
    REG_ERROR: "Error during registration, please try again",
    LOGIN_ERROR: "Error logging in, try again",
    USER_ERROR: "Error retrieving user data, please refresh the page",
    USERS_ERROR: "Error retrieving users, please refresh the page",
    LOCATION_ERROR:
      "Error when changing location, refresh the page and change the location again",
    QUEST_ERROR:
      "An error occurred when submitting the assignment, please refresh the page and submit the assignment again",
    LANG_ERROR:
      "Error when changing language, refresh the page and change the language again",
    EXP_ERROR: "Error while gaining experience, defeat the enemy again",
    CHAT_ERROR: "Error when writing to chat, write the message again",
    CHATS_ERROR:
      "An error occurred while receiving chat messages, please click the refresh button again",
    SUGGEST_ERROR: "Error sending proposal, please submit your proposal again",
    PROBLEM_ERROR: "Error submitting problem, please submit your problem again",
  },
});

export default localized;
